services:
  freetribe:
    image: bangcorrupt/freetribe
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    hostname: ft
    stdin_open: true
    tty: true
    volumes:
      - ./:/freetribe
